server:
  port: 6101
eureka:
  client:
    service-url:
      #服务注册地址,对应eureka的服务注册url
      defaultZone: http://localhost:7001/eureka/
spring:
  profiles:
 #   公共配置，后续转到configServer
    include:
    - api
  application:
    name: security-zuul
zuul:
  sensitive-headers: 
    