GET http://localhost:6101/login HTTP/1.1
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJxaXVxaXUiLCJpYXQiOjE1OTEzNDc3OTcsImV4cCI6MTU5MTM1NDk5N30.63tmJI9aW80QPZdLdXPc_fX9wEZtYTI1xSopYc3zTUY
Content-Type: application/json

{"username": "qiuqiu","password": "123"}
