spring:
  application:
    name: eureka-server
server:
  port: ${EUREKA-PORT:7001}
#Eureka配置
eureka:
  server:
  # 心跳保护
    enable-self-preservation: false
  client:
    # 指示此实例是否应向eureka服务器注册其信息以供其他人发现。在某些情况下，您不希望发现实例，而只想发现其他实例。
    register-with-eureka: true
    # 指示此客户端是否应从eureka服务器获取eureka注册表信息。
    fetch-registry: true
    service-url:
    # 从环境变量中获取其他的注册服务用于eureka集群。
      defaultZone: http://${EUREKA-IP:127.0.0.1}:7001/eureka/