server:
  port: 6101
spring:
  profiles:
 #   公共配置，后续转到configServer
    include:
    - api
  application:
    name: security-zuul
zuul:
  sensitive-headers: 
# 顶层网关的地址，用于重定向登录页面，就懒得写加config写注释了
security-zuul-top-gateway: http://localhost:6001
    