jwt:
  secret: bsIqMgs58mXxf+9/I+LV8Pji+/tVjaHDwwa7ytCd+iU=
  expiration: 7200000
  token: Authorization
spring:
  datasource:
    username: root
    password: 199598
    url: jdbc:mysql://localhost:3306/greenbirdoa?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  #pojo类的别名,这里指的是pojo包的包位置
  type-aliases-package: com.butch.apiutils.pojo
  #mapper.xml所在的位置
  mapper-locations: classpath*:mybatis/mapper/*Mapper.xml